import type React from "react";
import { useState } from "react";
import {
    Alert,
    Anchor,
    Badge,
    Button,
    Group,
    Stack,
    Text,
    TextInput,
    Textarea
} from "@mantine/core";
import { observer } from "mobx-react-lite";
import { resolveTemplate } from "#shared/templates/resolveTemplate.js";
import type { UpgradeWizardPresenter } from "../abstractions/UpgradeWizardPresenter.js";

interface PrStepProps {
    presenter: UpgradeWizardPresenter.Interface;
}

interface ISelectedPackage {
    name: string;
    targetVersion: string;
    currentVersion?: string;
    upgradeType?: string;
}

function buildPackagesTable(packages: ISelectedPackage[]): string {
    const header = "| Package | From | To | Type |\n|---------|------|----|------|";
    const rows = packages.map(
        p =>
            `| ${p.name} | ${p.currentVersion ?? "?"} | ${p.targetVersion} | ${p.upgradeType ?? "unknown"} |`
    );
    return [header, ...rows].join("\n");
}

export const PrStep = observer(function PrStep({ presenter }: PrStepProps): React.ReactNode {
    const { vm } = presenter;
    const step = vm.activeStep;

    const selectPackagesStep = vm.session?.steps.find(s => s.type === "select-packages");
    const packages = (selectPackagesStep?.input["packages"] ?? []) as ISelectedPackage[];
    const packagesTable = buildPackagesTable(packages);

    const templateContext = {
        count: packages.length,
        packagesTable,
        project: vm.projectName
    };

    const [title, setTitle] = useState(() =>
        resolveTemplate(
            vm.prTitleTemplate || "chore(deps): upgrade ${COUNT} packages",
            templateContext
        )
    );
    const [body, setBody] = useState(() =>
        resolveTemplate(
            vm.prBodyTemplate ||
                "## Dependency Upgrades\n\n${PACKAGES_TABLE}\n\n_Generated by Dependency Manager on ${YYYY}-${MM}-${DD}_",
            templateContext
        )
    );

    const handleCreate = async (): Promise<void> => {
        await presenter.executeStep("create-pr", { title, body });
    };

    const handleSkip = async (): Promise<void> => {
        await presenter.skipStep("create-pr");
    };

    if (step?.status === "completed") {
        const prUrl = String(step.result["url"]);
        return (
            <Alert color="green" title="Pull Request Created">
                <Anchor href={prUrl} target="_blank" size="sm">
                    {prUrl}
                </Anchor>
            </Alert>
        );
    }

    if (step?.status === "skipped" && step.result["reason"]) {
        return (
            <Alert color="yellow" title="Skipped">
                <Text size="sm">{String(step.result["reason"])}</Text>
            </Alert>
        );
    }

    return (
        <Stack gap="md">
            <Group gap="sm">
                <Text size="sm" c="dimmed">
                    Create a pull request for the upgrade.
                </Text>
                <Badge size="sm" variant="light">
                    {vm.session?.steps.find(s => s.type === "push")?.result["branch"]
                        ? "Ready"
                        : "Pending push"}
                </Badge>
            </Group>

            <TextInput
                label="PR Title"
                value={title}
                onChange={event => setTitle(event.currentTarget.value)}
            />

            <Textarea
                label="PR Body"
                value={body}
                onChange={event => setBody(event.currentTarget.value)}
                minRows={8}
                autosize
            />

            <Group justify="flex-end">
                <Button variant="default" onClick={handleSkip} disabled={vm.loading}>
                    Skip
                </Button>
                <Button onClick={handleCreate} loading={vm.loading} disabled={title.length === 0}>
                    Create Pull Request
                </Button>
            </Group>
        </Stack>
    );
});
