import { computed, makeAutoObservable, runInAction } from "mobx";
import { UpgradeWizardPresenter as Abstraction } from "./abstractions/UpgradeWizardPresenter.js";
import { UpgradeSessionsGateway } from "../../../features/UpgradeSessions/abstractions/UpgradeSessionsGateway.js";
import { UpgradeSessionsRepository } from "../../../features/UpgradeSessions/abstractions/UpgradeSessionsRepository.js";
import { ProjectsGateway } from "../../../features/Projects/abstractions/ProjectsGateway.js";
import { ProjectsRepository } from "../../../features/Projects/abstractions/ProjectsRepository.js";
import { LoadProjectsUseCase } from "../useCases/abstractions/LoadProjectsUseCase.js";
import { EventBridge } from "../../../infrastructure/Events/abstractions/EventBridge.js";
import "../../../infrastructure/Events/eventMap.js";
import { ChangelogTracker } from "../../Shared/ChangelogTracker.js";
import type { IStartChangelogTrackingInput } from "../../Shared/ChangelogTracker.js";
import { AppSettingsGateway } from "../../../features/AppSettings/abstractions/AppSettingsGateway.js";

const DEFAULT_BRANCH_TEMPLATE = "chore/update-dependencies-${YYYY}-${MM}-${DD}";
const DEFAULT_COMMIT_TEMPLATE = "chore: update dependencies ${YYYY}-${MM}-${DD}";
const DEFAULT_PR_TITLE_TEMPLATE = "chore(deps): upgrade ${COUNT} packages";
const DEFAULT_PR_BODY_TEMPLATE =
    "## Dependency Upgrades\n\n${PACKAGES_TABLE}\n\n_Generated by Dependency Manager on ${YYYY}-${MM}-${DD}_";

class UpgradeWizardPresenterImpl implements Abstraction.Interface {
    private loading = false;
    private error: string | null = null;
    private currentProjectId: string | null = null;
    private stepLogsValue: string[] = [];
    private branchTemplate = DEFAULT_BRANCH_TEMPLATE;
    private commitTemplate = DEFAULT_COMMIT_TEMPLATE;
    private prTitleTemplate = DEFAULT_PR_TITLE_TEMPLATE;
    private prBodyTemplate = DEFAULT_PR_BODY_TEMPLATE;

    private readonly changelogTracker: ChangelogTracker;

    private readonly handleStepProgress: EventBridge.Callback<"upgrade-session:step-progress">;
    private readonly handleStepComplete: EventBridge.Callback<"upgrade-session:step-complete">;

    public constructor(
        private readonly upgradeSessionsGateway: UpgradeSessionsGateway.Interface,
        private readonly upgradeSessionsRepository: UpgradeSessionsRepository.Interface,
        private readonly projectsGateway: ProjectsGateway.Interface,
        private readonly projectsRepository: ProjectsRepository.Interface,
        private readonly loadProjectsUseCase: LoadProjectsUseCase.Interface,
        private readonly eventBridge: EventBridge.Interface,
        private readonly appSettingsGateway: AppSettingsGateway.Interface
    ) {
        makeAutoObservable(this, { vm: computed });
        this.changelogTracker = new ChangelogTracker(this.eventBridge);

        this.handleStepProgress = data => {
            const session = this.upgradeSessionsRepository.getSession();
            if (session && data.sessionId === session.id) {
                runInAction(() => {
                    this.stepLogsValue.push(data.log);
                });
            }
        };

        this.handleStepComplete = data => {
            const session = this.upgradeSessionsRepository.getSession();
            if (session && data.sessionId === session.id) {
                void this.refreshSession();
            }
        };

        this.eventBridge.on("upgrade-session:step-progress", this.handleStepProgress);
        this.eventBridge.on("upgrade-session:step-complete", this.handleStepComplete);
    }

    public get vm(): Abstraction.ViewModel {
        const session = this.upgradeSessionsRepository.getSession();
        const activeStep = session?.steps.find(step => step.status === "active") ?? null;
        const project = this.currentProjectId
            ? this.projectsRepository.getProject(this.currentProjectId)
            : undefined;

        return {
            loading: this.loading,
            error: this.error,
            session,
            activeStep,
            projectName: project?.name ?? "",
            stepLogs: this.stepLogsValue,
            branchTemplate: this.branchTemplate,
            commitTemplate: this.commitTemplate,
            prTitleTemplate: this.prTitleTemplate,
            prBodyTemplate: this.prBodyTemplate,
            changelogState: this.changelogTracker.state
        };
    }

    // `preselected` is part of the presenter's public contract (see abstractions/UpgradeWizardPresenter.ts)
    // so callers can pass package names selected upstream (e.g. from ProjectDetail). The wizard
    // itself doesn't yet consume it — the select-packages step re-resolves target versions via its
    // own form. Reserved for a future task; not stored here to avoid an unused-field tsc error.
    public load = async (projectId: string, _preselected?: string[]): Promise<void> => {
        this.loading = true;
        this.error = null;
        this.currentProjectId = projectId;
        this.stepLogsValue = [];

        try {
            const [session, , appSettingsResult] = await Promise.all([
                this.upgradeSessionsGateway.createSession(projectId),
                this.loadProjectsUseCase.execute(),
                this.appSettingsGateway.list()
            ]);

            const appSettings = appSettingsResult.settings;
            const branchSetting = appSettings.find(s => s.key === "branch_template");
            const commitSetting = appSettings.find(s => s.key === "commit_template");
            const prTitleSetting = appSettings.find(s => s.key === "pr_title_template");
            const prBodySetting = appSettings.find(s => s.key === "pr_body_template");
            if (branchSetting) {
                this.branchTemplate = branchSetting.value;
            }
            if (commitSetting) {
                this.commitTemplate = commitSetting.value;
            }
            if (prTitleSetting) {
                this.prTitleTemplate = prTitleSetting.value;
            }
            if (prBodySetting) {
                this.prBodyTemplate = prBodySetting.value;
            }

            runInAction(() => {
                this.upgradeSessionsRepository.setSession(session);
            });
        } catch (error) {
            runInAction(() => {
                this.error =
                    error instanceof Error ? error.message : "Failed to start upgrade session";
            });
        } finally {
            runInAction(() => {
                this.loading = false;
            });
        }
    };

    public executeStep = async (
        stepType: string,
        input: Record<string, unknown>
    ): Promise<void> => {
        const session = this.upgradeSessionsRepository.getSession();
        if (!this.currentProjectId || !session) {
            return;
        }

        this.stepLogsValue = [];
        this.loading = true;
        this.error = null;
        try {
            const updated = await this.upgradeSessionsGateway.executeStep(
                this.currentProjectId,
                session.id,
                stepType,
                input
            );
            runInAction(() => {
                this.upgradeSessionsRepository.setSession(updated);
            });
        } catch (error) {
            runInAction(() => {
                this.error = error instanceof Error ? error.message : "Failed to execute step";
            });
        } finally {
            runInAction(() => {
                this.loading = false;
            });
        }
    };

    public skipStep = async (stepType: string): Promise<void> => {
        const session = this.upgradeSessionsRepository.getSession();
        if (!this.currentProjectId || !session) {
            return;
        }

        this.loading = true;
        this.error = null;
        try {
            const updated = await this.upgradeSessionsGateway.skipStep(
                this.currentProjectId,
                session.id,
                stepType
            );
            runInAction(() => {
                this.upgradeSessionsRepository.setSession(updated);
            });
        } catch (error) {
            runInAction(() => {
                this.error = error instanceof Error ? error.message : "Failed to skip step";
            });
        } finally {
            runInAction(() => {
                this.loading = false;
            });
        }
    };

    public abort = async (): Promise<void> => {
        const session = this.upgradeSessionsRepository.getSession();
        if (!this.currentProjectId || !session) {
            return;
        }

        this.loading = true;
        this.error = null;
        try {
            const updated = await this.upgradeSessionsGateway.abortSession(
                this.currentProjectId,
                session.id
            );
            runInAction(() => {
                this.upgradeSessionsRepository.setSession(updated);
            });
        } catch (error) {
            runInAction(() => {
                this.error = error instanceof Error ? error.message : "Failed to abort session";
            });
        } finally {
            runInAction(() => {
                this.loading = false;
            });
        }
    };

    public getChangelogs = async (
        packageName: string,
        from: string,
        to: string
    ): Promise<ProjectsGateway.ChangelogResult> => {
        return this.projectsGateway.getChangelogs(packageName, from, to);
    };

    public reResolveChangelogs = async (
        packageName: string,
        from: string,
        to: string
    ): Promise<ProjectsGateway.ChangelogResult> => {
        return this.projectsGateway.reResolveChangelogs(packageName, from, to);
    };

    public startChangelogTracking = (input: IStartChangelogTrackingInput): void => {
        this.changelogTracker.startTracking(input);
    };

    public stopChangelogTracking = (): void => {
        this.changelogTracker.stopTracking();
    };

    public dispose = (): void => {
        this.changelogTracker.dispose();
        this.eventBridge.off("upgrade-session:step-progress", this.handleStepProgress);
        this.eventBridge.off("upgrade-session:step-complete", this.handleStepComplete);
    };

    private refreshSession = async (): Promise<void> => {
        const session = this.upgradeSessionsRepository.getSession();
        if (!this.currentProjectId || !session) {
            return;
        }

        const updated = await this.upgradeSessionsGateway.getSession(
            this.currentProjectId,
            session.id
        );
        runInAction(() => {
            this.upgradeSessionsRepository.setSession(updated);
            this.stepLogsValue = [];
        });
    };
}

export const UpgradeWizardPresenter = Abstraction.createImplementation({
    implementation: UpgradeWizardPresenterImpl,
    dependencies: [
        UpgradeSessionsGateway,
        UpgradeSessionsRepository,
        ProjectsGateway,
        ProjectsRepository,
        LoadProjectsUseCase,
        EventBridge,
        AppSettingsGateway
    ]
});
