import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, writeFile, rm } from "fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { createContainer } from "#shared/index.js";
import { LockfileParserService } from "../abstractions/LockfileParserService.js";
import { LockfileParserService as LockfileParserServiceRegistration } from "../LockfileParserService.js";

// npm package-lock.json v3 fixture: express (depth 0) -> body-parser (depth 1)
// -> qs (depth 2), plus vitest declared as a devDependency (depth 0).
const NPM_PACKAGE_LOCK_V3 = JSON.stringify({
    name: "test-project",
    lockfileVersion: 3,
    packages: {
        "": {
            dependencies: { express: "^4.18.0" },
            devDependencies: { vitest: "^4.0.0" }
        },
        "node_modules/express": {
            version: "4.18.2",
            dependencies: { "body-parser": "1.20.2" }
        },
        "node_modules/express/node_modules/body-parser": {
            version: "1.20.2",
            dependencies: { qs: "6.11.0" }
        },
        "node_modules/express/node_modules/body-parser/node_modules/qs": {
            version: "6.11.0"
        },
        "node_modules/vitest": {
            version: "4.0.0"
        }
    }
});

const ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { express: "^4.18.0" },
    devDependencies: { vitest: "^4.0.0" }
});

const EMPTY_NPM_PACKAGE_LOCK_V3 = JSON.stringify({
    name: "empty-project",
    lockfileVersion: 3,
    packages: {}
});

// yarn.lock (Berry-style) fixture: express (depth 0) -> body-parser (depth 1)
// -> qs (depth 2), plus vitest declared as a devDependency (depth 0).
const YARN_LOCK_V1 = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"express@npm:^4.18.0":
  version: 4.18.2
  resolution: "express@npm:4.18.2"
  dependencies:
    body-parser: "npm:1.20.2"
  checksum: 10/abc123
  languageName: node
  linkType: hard

"body-parser@npm:1.20.2":
  version: 1.20.2
  resolution: "body-parser@npm:1.20.2"
  dependencies:
    qs: "npm:6.11.0"
  checksum: 10/def456
  languageName: node
  linkType: hard

"qs@npm:6.11.0":
  version: 6.11.0
  resolution: "qs@npm:6.11.0"
  checksum: 10/ghi789
  languageName: node
  linkType: hard

"vitest@npm:^4.0.0":
  version: 4.0.0
  resolution: "vitest@npm:4.0.0"
  checksum: 10/jkl012
  languageName: node
  linkType: hard
`;

// yarn.lock fixture where two different root packages depend on the same
// package name ("debug") via different ranges, resolving to two versions.
const YARN_LOCK_MULTIPLE_VERSIONS = `"pkg-a@npm:^1.0.0":
  version: 1.0.0
  resolution: "pkg-a@npm:1.0.0"
  dependencies:
    debug: "npm:^4.0.0"
  languageName: node
  linkType: hard

"pkg-b@npm:^1.0.0":
  version: 1.0.0
  resolution: "pkg-b@npm:1.0.0"
  dependencies:
    debug: "npm:^2.0.0"
  languageName: node
  linkType: hard

"debug@npm:^4.0.0":
  version: 4.3.4
  resolution: "debug@npm:4.3.4"
  languageName: node
  linkType: hard

"debug@npm:^2.0.0":
  version: 2.6.9
  resolution: "debug@npm:2.6.9"
  languageName: node
  linkType: hard
`;

// yarn.lock Classic v1 fixture: space-separated `version "x.y.z"` and
// `dep-name "range"` syntax (no colons), unlike Berry's `key: value` style.
const YARN_LOCK_CLASSIC_V1 = `express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  integrity sha512-...
  dependencies:
    body-parser "1.20.2"

body-parser@1.20.2:
  version "1.20.2"
  resolved "https://registry.yarnpkg.com/body-parser/-/body-parser-1.20.2.tgz"
  dependencies:
    qs "6.11.0"

qs@6.11.0:
  version "6.11.0"
  resolved "https://registry.yarnpkg.com/qs/-/qs-6.11.0.tgz"
`;

const YARN_CLASSIC_V1_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { express: "^4.18.0" }
});

// yarn.lock fixture covering a scoped package name (e.g. "@scope/pkg"),
// which requires skipping the scope's leading "@" when locating the "@"
// that separates the package name from its version/range.
const YARN_LOCK_SCOPED_PACKAGE = `"@scope/pkg@npm:^1.0.0":
  version: 1.2.3
  resolution: "@scope/pkg@npm:1.2.3"
  languageName: node
  linkType: hard
`;

const YARN_SCOPED_PACKAGE_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { "@scope/pkg": "^1.0.0" }
});

const YARN_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { express: "^4.18.0" },
    devDependencies: { vitest: "^4.0.0" }
});

const YARN_MULTIPLE_VERSIONS_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { "pkg-a": "^1.0.0", "pkg-b": "^1.0.0" }
});

// pnpm-lock.yaml fixture: express (depth 0) -> body-parser (depth 1)
// -> qs (depth 2), plus vitest declared as a devDependency (depth 0).
const PNPM_LOCK_YAML = `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      express:
        specifier: ^4.18.0
        version: 4.18.2
    devDependencies:
      vitest:
        specifier: ^4.0.0
        version: 4.0.0
packages:
  express@4.18.2:
    dependencies:
      body-parser: 1.20.2
  body-parser@1.20.2:
    dependencies:
      qs: 6.11.0
  qs@6.11.0: {}
`;

// pnpm-lock.yaml fixture with two workspace importers (monorepo).
const PNPM_LOCK_WORKSPACE_YAML = `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21
  packages/app:
    dependencies:
      express:
        specifier: ^4.18.0
        version: 4.18.2
packages:
  lodash@4.17.21: {}
  express@4.18.2:
    dependencies:
      body-parser: 1.20.2
  body-parser@1.20.2: {}
`;

const PNPM_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { express: "^4.18.0" },
    devDependencies: { vitest: "^4.0.0" }
});

// bun.lock (JSONC) fixture: express (depth 0) -> body-parser (depth 1)
// -> qs (depth 2), plus vitest declared as a devDependency (depth 0).
const BUN_LOCK_JSONC = `{
  // bun lockfile
  "lockfileVersion": 0,
  "workspaces": {
    "": {
      "dependencies": { "express": "^4.18.0" },
      "devDependencies": { "vitest": "^4.0.0" }
    }
  },
  "packages": {
    "express": ["express@4.18.2", { "dependencies": { "body-parser": "1.20.2" } }],
    "body-parser": ["body-parser@1.20.2", { "dependencies": { "qs": "6.11.0" } }],
    "qs": ["qs@6.11.0", {}],
    "vitest": ["vitest@4.0.0", {}]
  }
}
`;

const BUN_ROOT_PACKAGE_JSON = JSON.stringify({
    name: "test-project",
    dependencies: { express: "^4.18.0" },
    devDependencies: { vitest: "^4.0.0" }
});

describe("LockfileParserService", () => {
    let tempDir: string;
    let service: LockfileParserService.Interface;

    beforeEach(async () => {
        tempDir = await mkdtemp(join(tmpdir(), "dep-upgrader-lockfile-"));
        const container = createContainer();
        container.register(LockfileParserServiceRegistration).inSingletonScope();
        service = container.resolve(LockfileParserService);
    });

    afterEach(async () => {
        await rm(tempDir, { recursive: true, force: true });
    });

    describe("npm format", () => {
        beforeEach(async () => {
            await writeFile(join(tempDir, "package-lock.json"), NPM_PACKAGE_LOCK_V3, "utf-8");
            await writeFile(join(tempDir, "package.json"), ROOT_PACKAGE_JSON, "utf-8");
        });

        it("parses package-lock.json v3 packages format with depth from path nesting", async () => {
            const edges = await service.parse(tempDir, "npm");

            expect(edges).toEqual(
                expect.arrayContaining([
                    {
                        parentPackage: null,
                        parentVersion: null,
                        childPackage: "express",
                        childVersion: "4.18.2",
                        dependencyType: "dependency",
                        depth: 0
                    },
                    {
                        parentPackage: "express",
                        parentVersion: "4.18.2",
                        childPackage: "body-parser",
                        childVersion: "1.20.2",
                        dependencyType: "dependency",
                        depth: 1
                    },
                    {
                        parentPackage: "body-parser",
                        parentVersion: "1.20.2",
                        childPackage: "qs",
                        childVersion: "6.11.0",
                        dependencyType: "dependency",
                        depth: 2
                    }
                ])
            );
            expect(edges).toHaveLength(4);
        });

        it("identifies root dependencies (depth 0, parentPackage null) vs transitive (depth 1+)", async () => {
            const edges = await service.parse(tempDir, "npm");

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express.depth).toBe(0);
            expect(express.parentPackage).toBeNull();

            const bodyParser = edges.find(edge => edge.childPackage === "body-parser")!;
            expect(bodyParser.depth).toBe(1);
            expect(bodyParser.parentPackage).toBe("express");

            const qs = edges.find(edge => edge.childPackage === "qs")!;
            expect(qs.depth).toBe(2);
            expect(qs.parentPackage).toBe("body-parser");
        });

        it("classifies depth-0 packages declared in root package.json devDependencies", async () => {
            const edges = await service.parse(tempDir, "npm");

            const vitest = edges.find(edge => edge.childPackage === "vitest")!;
            expect(vitest).toEqual({
                parentPackage: null,
                parentVersion: null,
                childPackage: "vitest",
                childVersion: "4.0.0",
                dependencyType: "devDependency",
                depth: 0
            });

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express.dependencyType).toBe("dependency");
        });
    });

    it("returns an empty array for an empty packages object", async () => {
        await writeFile(join(tempDir, "package-lock.json"), EMPTY_NPM_PACKAGE_LOCK_V3, "utf-8");
        await writeFile(join(tempDir, "package.json"), ROOT_PACKAGE_JSON, "utf-8");

        const edges = await service.parse(tempDir, "npm");
        expect(edges).toEqual([]);
    });

    it("returns an empty array when the lockfile doesn't exist", async () => {
        await writeFile(join(tempDir, "package.json"), ROOT_PACKAGE_JSON, "utf-8");

        const edges = await service.parse(tempDir, "npm");
        expect(edges).toEqual([]);
    });

    it("returns an empty array for malformed lockfile JSON", async () => {
        await writeFile(join(tempDir, "package-lock.json"), "not valid json{{{", "utf-8");
        await writeFile(join(tempDir, "package.json"), ROOT_PACKAGE_JSON, "utf-8");

        const edges = await service.parse(tempDir, "npm");
        expect(edges).toEqual([]);
    });

    it("still parses when the root package.json is missing (no devDependency classification)", async () => {
        await writeFile(join(tempDir, "package-lock.json"), NPM_PACKAGE_LOCK_V3, "utf-8");

        const edges = await service.parse(tempDir, "npm");
        const vitest = edges.find(edge => edge.childPackage === "vitest")!;
        expect(vitest.dependencyType).toBe("dependency");
    });

    describe("yarn format", () => {
        beforeEach(async () => {
            await writeFile(join(tempDir, "yarn.lock"), YARN_LOCK_V1, "utf-8");
            await writeFile(join(tempDir, "package.json"), YARN_ROOT_PACKAGE_JSON, "utf-8");
        });

        it("parses yarn.lock v1 format entries with dependencies maps", async () => {
            const edges = await service.parse(tempDir, "yarn");

            expect(edges).toEqual(
                expect.arrayContaining([
                    {
                        parentPackage: null,
                        parentVersion: null,
                        childPackage: "express",
                        childVersion: "4.18.2",
                        dependencyType: "dependency",
                        depth: 0
                    },
                    {
                        parentPackage: "express",
                        parentVersion: "4.18.2",
                        childPackage: "body-parser",
                        childVersion: "1.20.2",
                        dependencyType: "dependency",
                        depth: 1
                    },
                    {
                        parentPackage: "body-parser",
                        parentVersion: "1.20.2",
                        childPackage: "qs",
                        childVersion: "6.11.0",
                        dependencyType: "dependency",
                        depth: 2
                    }
                ])
            );
        });

        it("cross-references package.json to identify root (depth 0) vs transitive deps", async () => {
            const edges = await service.parse(tempDir, "yarn");

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express.depth).toBe(0);
            expect(express.parentPackage).toBeNull();

            const bodyParser = edges.find(edge => edge.childPackage === "body-parser")!;
            expect(bodyParser.depth).toBe(1);
            expect(bodyParser.parentPackage).toBe("express");

            const vitest = edges.find(edge => edge.childPackage === "vitest")!;
            expect(vitest.depth).toBe(0);
            expect(vitest.dependencyType).toBe("devDependency");
        });

        it("handles multiple versions of the same package resolved via different ranges", async () => {
            await writeFile(join(tempDir, "yarn.lock"), YARN_LOCK_MULTIPLE_VERSIONS, "utf-8");
            await writeFile(
                join(tempDir, "package.json"),
                YARN_MULTIPLE_VERSIONS_ROOT_PACKAGE_JSON,
                "utf-8"
            );

            const edges = await service.parse(tempDir, "yarn");

            const debugEdges = edges.filter(edge => edge.childPackage === "debug");
            expect(debugEdges).toHaveLength(2);

            const debugViaPkgA = debugEdges.find(edge => edge.parentPackage === "pkg-a")!;
            expect(debugViaPkgA.childVersion).toBe("4.3.4");

            const debugViaPkgB = debugEdges.find(edge => edge.parentPackage === "pkg-b")!;
            expect(debugViaPkgB.childVersion).toBe("2.6.9");
        });

        it("parses Classic v1 format (space-separated version/dependencies, no colons)", async () => {
            await writeFile(join(tempDir, "yarn.lock"), YARN_LOCK_CLASSIC_V1, "utf-8");
            await writeFile(
                join(tempDir, "package.json"),
                YARN_CLASSIC_V1_ROOT_PACKAGE_JSON,
                "utf-8"
            );

            const edges = await service.parse(tempDir, "yarn");

            expect(edges).toEqual(
                expect.arrayContaining([
                    {
                        parentPackage: null,
                        parentVersion: null,
                        childPackage: "express",
                        childVersion: "4.18.2",
                        dependencyType: "dependency",
                        depth: 0
                    },
                    {
                        parentPackage: "express",
                        parentVersion: "4.18.2",
                        childPackage: "body-parser",
                        childVersion: "1.20.2",
                        dependencyType: "dependency",
                        depth: 1
                    },
                    {
                        parentPackage: "body-parser",
                        parentVersion: "1.20.2",
                        childPackage: "qs",
                        childVersion: "6.11.0",
                        dependencyType: "dependency",
                        depth: 2
                    }
                ])
            );
        });

        it("extracts the correct package name for a scoped package (@scope/pkg)", async () => {
            await writeFile(join(tempDir, "yarn.lock"), YARN_LOCK_SCOPED_PACKAGE, "utf-8");
            await writeFile(
                join(tempDir, "package.json"),
                YARN_SCOPED_PACKAGE_ROOT_PACKAGE_JSON,
                "utf-8"
            );

            const edges = await service.parse(tempDir, "yarn");

            expect(edges).toEqual([
                {
                    parentPackage: null,
                    parentVersion: null,
                    childPackage: "@scope/pkg",
                    childVersion: "1.2.3",
                    dependencyType: "dependency",
                    depth: 0
                }
            ]);
        });

        it("returns an empty array for an empty yarn.lock file", async () => {
            await writeFile(join(tempDir, "yarn.lock"), "", "utf-8");

            const edges = await service.parse(tempDir, "yarn");
            expect(edges).toEqual([]);
        });

        it("returns an empty array when yarn.lock doesn't exist", async () => {
            await rm(join(tempDir, "yarn.lock"));

            const edges = await service.parse(tempDir, "yarn");
            expect(edges).toEqual([]);
        });
    });

    describe("pnpm format", () => {
        beforeEach(async () => {
            await writeFile(join(tempDir, "pnpm-lock.yaml"), PNPM_LOCK_YAML, "utf-8");
            await writeFile(join(tempDir, "package.json"), PNPM_ROOT_PACKAGE_JSON, "utf-8");
        });

        it("parses the importers section for direct deps (depth 0)", async () => {
            const edges = await service.parse(tempDir, "pnpm");

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express).toEqual({
                parentPackage: null,
                parentVersion: null,
                childPackage: "express",
                childVersion: "4.18.2",
                dependencyType: "dependency",
                depth: 0
            });

            const vitest = edges.find(edge => edge.childPackage === "vitest")!;
            expect(vitest.dependencyType).toBe("devDependency");
            expect(vitest.depth).toBe(0);
        });

        it("parses the packages section for transitive deps", async () => {
            const edges = await service.parse(tempDir, "pnpm");

            const bodyParser = edges.find(edge => edge.childPackage === "body-parser")!;
            expect(bodyParser.depth).toBe(1);
            expect(bodyParser.parentPackage).toBe("express");

            const qs = edges.find(edge => edge.childPackage === "qs")!;
            expect(qs.depth).toBe(2);
            expect(qs.parentPackage).toBe("body-parser");
        });

        it("handles a workspace monorepo structure with multiple importers", async () => {
            await writeFile(join(tempDir, "pnpm-lock.yaml"), PNPM_LOCK_WORKSPACE_YAML, "utf-8");

            const edges = await service.parse(tempDir, "pnpm");

            const lodash = edges.find(edge => edge.childPackage === "lodash")!;
            expect(lodash.depth).toBe(0);

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express.depth).toBe(0);

            const bodyParser = edges.find(edge => edge.childPackage === "body-parser")!;
            expect(bodyParser.depth).toBe(1);
            expect(bodyParser.parentPackage).toBe("express");
        });

        it("returns an empty array when pnpm-lock.yaml doesn't exist", async () => {
            await rm(join(tempDir, "pnpm-lock.yaml"));

            const edges = await service.parse(tempDir, "pnpm");
            expect(edges).toEqual([]);
        });
    });

    describe("bun format", () => {
        beforeEach(async () => {
            await writeFile(join(tempDir, "bun.lock"), BUN_LOCK_JSONC, "utf-8");
            await writeFile(join(tempDir, "package.json"), BUN_ROOT_PACKAGE_JSON, "utf-8");
        });

        it("parses bun.lock JSONC format and strips comments", async () => {
            const edges = await service.parse(tempDir, "bun");

            const express = edges.find(edge => edge.childPackage === "express")!;
            expect(express).toEqual({
                parentPackage: null,
                parentVersion: null,
                childPackage: "express",
                childVersion: "4.18.2",
                dependencyType: "dependency",
                depth: 0
            });
        });

        it("extracts dependency edges from packages tuples", async () => {
            const edges = await service.parse(tempDir, "bun");

            const bodyParser = edges.find(edge => edge.childPackage === "body-parser")!;
            expect(bodyParser.depth).toBe(1);
            expect(bodyParser.parentPackage).toBe("express");

            const qs = edges.find(edge => edge.childPackage === "qs")!;
            expect(qs.depth).toBe(2);
            expect(qs.parentPackage).toBe("body-parser");

            const vitest = edges.find(edge => edge.childPackage === "vitest")!;
            expect(vitest.dependencyType).toBe("devDependency");
            expect(vitest.depth).toBe(0);
        });

        it("returns an empty array when bun.lock doesn't exist", async () => {
            await rm(join(tempDir, "bun.lock"));

            const edges = await service.parse(tempDir, "bun");
            expect(edges).toEqual([]);
        });

        it("returns an empty array for malformed bun.lock JSON", async () => {
            await writeFile(join(tempDir, "bun.lock"), "not valid json{{{", "utf-8");

            const edges = await service.parse(tempDir, "bun");
            expect(edges).toEqual([]);
        });
    });
});
